# Generated by Django 4.2.13 on 2024-06-07 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meno', models.CharField(max_length=20)),
                ('priezvisko', models.CharField(max_length=20)),
                ('odbor', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('heslo', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Študent',
                'verbose_name_plural': 'Študenti',
                'ordering': ['priezvisko'],
            },
        ),
        migrations.CreateModel(
            name='Trieda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Trieda',
                'verbose_name_plural': 'Triedy',
                'ordering': ['nazov'],
            },
        ),
        migrations.CreateModel(
            name='Ucitel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titul', models.CharField(max_length=20)),
                ('meno', models.CharField(max_length=20)),
                ('priezvisko', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('heslo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=20)),
                ('popis', models.TextField(blank=True)),
                ('dostupnost', models.CharField(choices=[('VO', 'Voľne'), ('CA', 'Čakajúce'), ('OB', 'Obsadené')], max_length=300)),
                ('konzultant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='soc.ucitel')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='soc.student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='trieda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='soc.trieda'),
        ),
    ]
